version: "3.9"
services:
  jeecg-mysql:
    container_name: jeecg-mysql
    image: jeecg-mysql:8.0
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/docker/jeecg-mysql/data:/var/lib/mysql"
    command: [ "--lower_case_table_names=1", "--log-bin=mysql-bin", "--binlog-format=ROW", "--server_id=1", "--character-set-server=utf8mb4", "--default-authentication-plugin=mysql_native_password", "--collation-server=utf8mb4_unicode_ci" ]
    restart: always
  jeecg-redis:
    container_name: jeecg-redis
    image: jeecg-redis:6.0
    build: ./redis
    ports:
      - "6380:6379"
    volumes:
      # 时区同步
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      #      - "/opt/docker/jeecg-redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "/opt/docker/jeecg-redis/data:/data"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    restart: always